module.exports = function ({addUtilities}) {
    const utilities = {
        '.primary-gray': {
            '--color-primary-50': 'var(--color-gray-50) !important',
            '--color-primary-100': 'var(--color-gray-100) !important',
            '--color-primary-200': 'var(--color-gray-200) !important',
            '--color-primary-300': 'var(--color-gray-300) !important',
            '--color-primary-400': 'var(--color-gray-400) !important',
            '--color-primary-500': 'var(--color-gray-500) !important',
            '--color-primary-600': 'var(--color-gray-600) !important',
            '--color-primary-700': 'var(--color-gray-700) !important',
            '--color-primary-800': 'var(--color-gray-800) !important',
            '--color-primary-900': 'var(--color-gray-900) !important',
        },
        '.primary-red': {
            '--color-primary-50': 'var(--color-red-50) !important',
            '--color-primary-100': 'var(--color-red-100) !important',
            '--color-primary-200': 'var(--color-red-200) !important',
            '--color-primary-300': 'var(--color-red-300) !important',
            '--color-primary-400': 'var(--color-red-400) !important',
            '--color-primary-500': 'var(--color-red-500) !important',
            '--color-primary-600': 'var(--color-red-600) !important',
            '--color-primary-700': 'var(--color-red-700) !important',
            '--color-primary-800': 'var(--color-red-800) !important',
            '--color-primary-900': 'var(--color-red-900) !important',
        },
        '.primary-orange': {
            '--color-primary-50': 'var(--color-orange-50) !important',
            '--color-primary-100': 'var(--color-orange-100) !important',
            '--color-primary-200': 'var(--color-orange-200) !important',
            '--color-primary-300': 'var(--color-orange-300) !important',
            '--color-primary-400': 'var(--color-orange-400) !important',
            '--color-primary-500': 'var(--color-orange-500) !important',
            '--color-primary-600': 'var(--color-orange-600) !important',
            '--color-primary-700': 'var(--color-orange-700) !important',
            '--color-primary-800': 'var(--color-orange-800) !important',
            '--color-primary-900': 'var(--color-orange-900) !important',
        },
        '.primary-yellow': {
            '--color-primary-50': 'var(--color-yellow-50) !important',
            '--color-primary-100': 'var(--color-yellow-100) !important',
            '--color-primary-200': 'var(--color-yellow-200) !important',
            '--color-primary-300': 'var(--color-yellow-300) !important',
            '--color-primary-400': 'var(--color-yellow-400) !important',
            '--color-primary-500': 'var(--color-yellow-500) !important',
            '--color-primary-600': 'var(--color-yellow-600) !important',
            '--color-primary-700': 'var(--color-yellow-700) !important',
            '--color-primary-800': 'var(--color-yellow-800) !important',
            '--color-primary-900': 'var(--color-yellow-900) !important',
        },
        '.primary-green': {
            '--color-primary-50': 'var(--color-green-50) !important',
            '--color-primary-100': 'var(--color-green-100) !important',
            '--color-primary-200': 'var(--color-green-200) !important',
            '--color-primary-300': 'var(--color-green-300) !important',
            '--color-primary-400': 'var(--color-green-400) !important',
            '--color-primary-500': 'var(--color-green-500) !important',
            '--color-primary-600': 'var(--color-green-600) !important',
            '--color-primary-700': 'var(--color-green-700) !important',
            '--color-primary-800': 'var(--color-green-800) !important',
            '--color-primary-900': 'var(--color-green-900) !important',
        },
        '.primary-teal': {
            ':root': {
                '--color-primary-50': 'var(--color-teal-50) !important',
                '--color-primary-100': 'var(--color-teal-100) !important',
                '--color-primary-200': 'var(--color-teal-200) !important',
                '--color-primary-300': 'var(--color-teal-300) !important',
                '--color-primary-400': 'var(--color-teal-400) !important',
                '--color-primary-500': 'var(--color-teal-500) !important',
                '--color-primary-600': 'var(--color-teal-600) !important',
                '--color-primary-700': 'var(--color-teal-700) !important',
                '--color-primary-800': 'var(--color-teal-800) !important',
                '--color-primary-900': 'var(--color-teal-900) !important',
            }
        },
        '.primary-blue': {
            '--color-primary-50': 'var(--color-blue-50) !important',
            '--color-primary-100': 'var(--color-blue-100) !important',
            '--color-primary-200': 'var(--color-blue-200) !important',
            '--color-primary-300': 'var(--color-blue-300) !important',
            '--color-primary-400': 'var(--color-blue-400) !important',
            '--color-primary-500': 'var(--color-blue-500) !important',
            '--color-primary-600': 'var(--color-blue-600) !important',
            '--color-primary-700': 'var(--color-blue-700) !important',
            '--color-primary-800': 'var(--color-blue-800) !important',
            '--color-primary-900': 'var(--color-blue-900) !important',
        },
        '.primary-indigo': {
            '--color-primary-50': 'var(--color-indigo-50) !important',
            '--color-primary-100': 'var(--color-indigo-100) !important',
            '--color-primary-200': 'var(--color-indigo-200) !important',
            '--color-primary-300': 'var(--color-indigo-300) !important',
            '--color-primary-400': 'var(--color-indigo-400) !important',
            '--color-primary-500': 'var(--color-indigo-500) !important',
            '--color-primary-600': 'var(--color-indigo-600) !important',
            '--color-primary-700': 'var(--color-indigo-700) !important',
            '--color-primary-800': 'var(--color-indigo-800) !important',
            '--color-primary-900': 'var(--color-indigo-900) !important',
        },
        '.primary-purple': {
            '--color-primary-50': 'var(--color-purple-50) !important',
            '--color-primary-100': 'var(--color-purple-100) !important',
            '--color-primary-200': 'var(--color-purple-200) !important',
            '--color-primary-300': 'var(--color-purple-300) !important',
            '--color-primary-400': 'var(--color-purple-400) !important',
            '--color-primary-500': 'var(--color-purple-500) !important',
            '--color-primary-600': 'var(--color-purple-600) !important',
            '--color-primary-700': 'var(--color-purple-700) !important',
            '--color-primary-800': 'var(--color-purple-800) !important',
            '--color-primary-900': 'var(--color-purple-900) !important',
        },
        '.primary-pink': {
            '--color-primary-50': 'var(--color-pink-50) !important',
            '--color-primary-100': 'var(--color-pink-100) !important',
            '--color-primary-200': 'var(--color-pink-200) !important',
            '--color-primary-300': 'var(--color-pink-300) !important',
            '--color-primary-400': 'var(--color-pink-400) !important',
            '--color-primary-500': 'var(--color-pink-500) !important',
            '--color-primary-600': 'var(--color-pink-600) !important',
            '--color-primary-700': 'var(--color-pink-700) !important',
            '--color-primary-800': 'var(--color-pink-800) !important',
            '--color-primary-900': 'var(--color-pink-900) !important',
        },
    };

    addUtilities(utilities)
};
